---
title: "Recommender System"
---

While we talk about marketing, most of us will think about the diverse ads on the television; While we talk about machine learning, most of us will think about the robot science. However, in real world, marketing and machine learning is everywhere. And sometimes, two concepts that seems to be from two totally different realm can combine to help business. For example, personizing the replying message so that customers feel connected.

In this project, we will lead you through a combination of machine learning and marketing that mainly focus on the content optimization aspect: the recommender system and let you understand how the system actually works.

All of the graphs and code can be found in the MBAN GitHub repository, feel free to download it and modify the numbers for your use case. The Jupyter notebook can be opened in the syzygy.

<a href="https://pims.syzygy.ca/jupyter/user/qingkangcao/git-pull?repo=https%3A%2F%2Fgithub.com%2FMaster-of-Business-Analytics%2FProject_09_Web_Scraping&urlpath=tree%2FProject_09_Web_Scraping%2F" target="_blank" class="button">Launch Syzygy</a>

## Business Problem

Here we can use the movie industry as an example to illustrate how the recommender system can actually be applied into a business context. The traditional movie content provider systems don't care about the general taste of the customers because how they get their revenue is irrelevant to their ability to tell their customers' taste. On the other words, the traditional movie seller only focus on the most welcomed movie and try to sell as many as possible. However, with the introduction of the age of internet, how current movie sellers makes money actually changes. Their income is now highly correlated with how long custoemrs spend on the site to watch the movie. So here the recommender system is required to make sure customers got the best recommendation and spend more time on the website.

We will use the movie rating dataset to try to duplicate that process

## Recommender System and Machine Learning


```python
import pandas as pd 
import numpy as np 
df1=pd.read_csv('../input/tmdb-movie-metadata/tmdb_5000_credits.csv')
df2=pd.read_csv('../input/tmdb-movie-metadata/tmdb_5000_movies.csv')

df1.columns = ['id','tittle','cast','crew']
df2= df2.merge(df1,on='id')

df2.head(5)
```
```
WIP
```

```python
A= df2['vote_average'].mean()
B= df2['vote_count'].quantile(0.9)
```
